name: ChatLog
descriptipn: Chatlog generator to report players
version: 1.14.1
api-version: 1.13
author: McLive
website: www.freecraft.eu

main: eu.mclive.ChatLog.ChatLog

commands:
  chatlog:
    aliases:
      - chatreport
    description: Generate a chatlog to report players

permissions:
  chatlog.command:
    description: Allows /chatlog

  chatlog.reload:
    description: Allows reloading the plugin with /chatlog reload